### ISSUE TITLE
eig_decomp should use SVD rather than Eigen decomposition

### ISSUE THREAD

**Issue by gavinsimpson** [Auerilas/ecopy#1]
SVD is generally recommended as the way to compute PCA, particularly from a numerical accuracy point of view. vegan uses SVD as does the recommended `prcomp()` function in base R. A further benefit of SVD is that the Eigen decomposition approach requires at least as many rows as columns in the data matrix. The SVD approach, however, can fit PCA when there are more columns than rows.

**Comment by Auerilas** [comment]
Fixed!
