### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by prubbens** [Auerilas/ecopy#15]
Installed `ecopy` using the conda installer: 
     
    conda install ecopy

Which worked succesfully, but trying to import it in Python 3 gives me the following error: 

    ImportError: numpy.core.multiarray failed to import

Any ideas how to resolve this?

**Comment by Auerilas** [comment]
I think this is a local issue on your machine with conflicting versions of numpy:
https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import
https://github.com/tensorflow/tensorflow/issues/559
https://python-forum.io/Thread-ImportError-numpy-core-multiarray-failed-to-import
