### ISSUE TITLE
Setup attempts to overwrite numpy in python 3.x?

### ISSUE THREAD

**Issue by Auerilas** [Auerilas/ecopy#3]
I just received an email that attempting to install EcoPy under Python 3.4.1 attempts to overwrite numpy and other modules. I'm not sure how to resolve this, nor do I have experience with Python 3.4.

**Comment by Auerilas** [comment]
@grovduck any ideas? I'm using your setup.py file that you provided, so I'm hoping you might have a fix for this.

**Comment by grovduck** [comment]
@Auerilas I'm guessing that the user has < numpy 1.7 (see `install_requires` within `setup.py`)?  It would be helpful to see the install log messages as well as their results of `pip freeze --all`.

I am by no means an expert on installs but this one seems pretty straightforward.  I've only installed on python 2.x, but could try 3.x if the user is still having issues

**Comment by Auerilas** [comment]
I'm not sure if this is still an issue. I've been gone for a bit. I'm closing it as I've not heard of this occurring since.
