### ISSUE TITLE
ImportError: No module named 'pca'

### ISSUE THREAD

**Issue by aabversteeg** [Auerilas/ecopy#5]
When I try to import ecopy I get this error:

ImportErrorTraceback (most recent call last)
<ipython-input-152-17d10be841b2> in <module>()
      3 import re
      4 import operator
----> 5 import ecopy

/opt/conda/lib/python3.5/site-packages/ecopy/**init**.py in <module>()
      3 
      4 from .regression import *
----> 5 from .ordination import *
      6 from .diversity import *
      7 from .matrix_comp import *

/opt/conda/lib/python3.5/site-packages/ecopy/ordination/**init**.py in <module>()
----> 1 from pca import pca
      2 from correspondance import ca
      3 from pcoa import pcoa
      4 from distance import distance
      5 from transform import transform

ImportError: No module named 'pca'

**Comment by Auerilas** [comment]
Hi Ben,

Are you using Python 3? I’m aware of this issue and I have it fixed on my development copy. I’m attempting to upload the newest version now, but run into some issues. I’ll let you know when I get it sorted.

Nathan Lemoine

## 

Research Scientist I
USDA NIFA-AFRI Postdoctoral Fellow

Colorado State University
Department of Biology
Graduate Degree Program in Ecology

**Comment by aabversteeg** [comment]
Hi Nathan,

Thank you for your reply. Yes, I do use Python 3.
I'm looking forward to the release!

Benjamin

2016-10-07 15:59 GMT+02:00 Auerilas notifications@github.com:

> Hi Ben,
> 
> Are you using Python 3? I’m aware of this issue and I have it fixed on my
> development copy. I’m attempting to upload the newest version now, but run
> into some issues. I’ll let you know when I get it sorted.
> 
> Nathan Lemoine
> 
> ## 
> 
> Research Scientist I
> USDA NIFA-AFRI Postdoctoral Fellow
> 
> Colorado State University
> Department of Biology
> Graduate Degree Program in Ecology
>

**Comment by Auerilas** [comment]
Hi @aabversteeg 

I just upgraded and hopefully added Python 3 compatability (at least it works on my system). Go ahead and give it a shot now.
